### ISSUE TITLE
YTS Command

### ISSUE THREAD

**Issue by Peketr** [2colours/rad.io#64]
if the yt target is a playlist shuffle before starting the first item.

(Majd ránézek én, csak le akartam írni, hogy ne felejtsem el)

**Comment by 2colours** [comment]
Ezt elvileg megoldottam: https://github.com/2colours/rad.io/commit/72d417b574f487d3b892067ba89b47a6b7684ac7
A yt parancs kapott egy opcionális preshuffle boolean paramétert.
